### ISSUE TITLE
[FEAT]: Rename repository or container image

### ISSUE THREAD

**Issue by karras** [projectpotos/potos-iso-builder#5]
### Description

I noticed the different names of this repository (`potos-image`) and the provided container image (`potos-iso-builder`). After some thoughts I think it could make sense to rename the repository itself also to `potos-iso-builder`. This seems to better capture the intention and content of the repo as it mainly contains the glue code but not the image itself. In addition using the term `iso` is probably also better to avoid confusion with image like in "picture".

What do you think? Should we rename the repository to `potos-iso-builder`?

**Comment by nis65** [comment]
I like the idea. It also implies that once potos is able to generate ready made disk images for VMs, we would have a new repo `potos-vm-builder` (or so)...

**Comment by fadnincx** [comment]
Done: repo is renamed :heavy_check_mark:
